---
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4.4"
  - "3.5"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible
  - pip uninstall six --yes
  - pip install httplib2 six
  - pip install --upgrade six
  - pip freeze

script:
  - python run-tests.py
