---
language: python
cache: pip
python:
  - "2.7"
  - "3.3"
  - "3.4.4"
  - "3.5"
  - "3.6"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  - pip install ansible
  - pip install vcrpy

script:
  - python tests/scripts/preflight.py
  - python tests/scripts/run-tests.py
  - python tests/scripts/postflight.py
